CC=clang
CXX=clang++
LDFLAGS+= -lstdc++ -framework Cocoa -framework OpenGL -framework QuartzCore -m64 -lpthread
CFLAGS+= -framework Cocoa -framework OpenGL -framework QuartzCore -D TARGET_OS_MAC -m64 -x objective-c

APP_OUT=bin/snow