CC=clang
CXX=clang++
LDFLAGS+= -lstdc++ -framework Cocoa -framework OpenGL -framework QuartzCore -m64 -lSDLmain -lSDL -lpthread -pthread
CFLAGS+= -framework Cocoa -framework OpenGL -framework QuartzCore -D TARGET_OS_MAC -m64

APP_OUT=bin/snow