CC?=clang
CXX?=clang++
LDFLAGS+= -lstdc++ -framework Cocoa -framework OpenGL -framework QuartzCore -m64 -lpthread
CFLAGS+= -D TARGET_OS_MAC -m64 -x objective-c -fpie -fstack-protector-all -D_FORTIFY_SOURCE=2 -fobjc-arc

APP_OUT=bin/snow